version: "3.9"

services:
  mssql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    env_file: .env
    ports:
      - "${SQLSERVER_LOCAL_PORT}:${SQLSERVER_DOCKER_PORT}"
    environment:
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      ACCEPT_EULA: Y
    networks:
      - my_network
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SQLSERVER_SA_PASSWORD -Q 'IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = \"$SQLSERVER_DATABASE\") CREATE DATABASE $SQLSERVER_DATABASE;' && wait"

  api-service:
    container_name: api-service
    image: foxfessor/api-service:1.0
    restart: always
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      spring.datasource.url: jdbc:sqlserver://mssql-server:$SQLSERVER_DOCKER_PORT;databaseName=$SQLSERVER_DATABASE;encrypt=true;trustServerCertificate=true
    networks:
      - my_network
    depends_on:
      - mssql-server

networks:
  my_network:
    driver: bridge